#include<iostream.h>
#include<conio.h>
main()
{
clrscr();
cout<<"D is a print"<<endl;
cout<<"#-#-#-#-#"<<endl;
cout<<"    #    #"<<endl;
cout<<"    #    #"<<endl;
cout<<"    #    #"<<endl;
cout<<"#-#-#-#-#"<<endl;

cout<<"B is a pront"<<endl;


cout<<"#-#-#-#"<<endl;
cout<<"#     #"<<endl;
cout<<"#     #"<<endl;
cout<<"#  #  "<<endl;
cout<<"#     #"<<endl;
cout<<"#     #"<<endl;
cout<<"#-#-#-#"<<endl;
getch();
}
